### ISSUE TITLE
Wrong portainer configuration

### ISSUE THREAD

**Issue by Austrum-lab** [jelastic-jps/docker#12]
Hello!

When i creating docker engine env in Jelastic via marketplace with portainer addon container creating with -p 443:9000. It's wrong (443 to http forwarding).

Here:
docker/addons/portainer.jps (33 and 43)
'-p ${settings.port}:9000'
Need to be:
'-p ${settings.port}:9443' or '-p ${settings.port}:9443 -p 8080:9000'

**Comment by SlavaKatiukha** [comment]
Thank you for your report.The issue is fixed (#13 )
